name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-buildx-action@v1

            - name: Set up Docker container
              uses: docker://python:3.12-bullseye

            - name: Install Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Set up Poetry
              run: |
                  pip install poetry
                  poetry config virtualenvs.create false

            - name: Install dependencies
              run: make install

            - name: Run formatting check
              run: make fmt-check

            - name: Run linting
              run: make lint

            - name: Run type checking
              run: make typecheck
