name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Set up Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install dependencies
              run: make install

            - name: Setup Environment

              env:
                  ACTOR: ${{github.actor}}
                  NAME: ${{ env.NAME }}
                  DB_USER: ${{ secrets.DB_USER }}
                  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
                  CLUSTER_NAME: ${{secrets.CLUSTER_NAME}}
                  DB_NAME: ${{secrets.DB_NAME}}
              run: |
                  echo Hello ${env.NAME}
                  echo "DB_USER=${{secrets.DB_USER}}" >> ./gsp/.env
                  echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> ./gsp/.env
                  echo "CLUSTER_NAME=${{secrets.CLUSTER_NAME}}" >> ./gsp/.env
                  echo "DB_NAME=${{secrets.DB_NAME}}" >> ./gsp/.env
                  cat ./gsp/.env

            - name: Convert Jupyter notebooks to Python scripts
              run: make convert

            - name: Run formatting check
              run: make fmt-check

            - name: Run linting
              run: make lint

            - name: Run type checking
              run: make typecheck

            - name: Run coverage
              run: make test-coverage

            - name: Upload coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: coverage
                  path: ./gsp/.coverage
