name: Release

on:
    push:
        branches:
            - main
        tags:
            - "*"

jobs:
    release:
        if: contains(github.event.head_commit.message, '#major') || contains(github.event.head_commit.message, '#minor') || contains(github.event.head_commit.message, '#patch')
        runs-on: ubuntu-latest
        environment: testing

        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Set up Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install dependencies
              run: make install

            - name: Setup Environment
              run: |
                  echo "DB_USER=${{secrets.DB_USER}}" >> ./gsp/.env
                  echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> ./gsp/.env
                  echo "DB_NAME=${{secrets.DB_NAME}}" >> ./gsp/.env
                  echo "CLUSTER_NAME=${{secrets.CLUSTER_NAME}}" >> ./gsp/.env

            - name: Run formatting check
              run: make fmt-check

            - name: Run linting
              run: make lint

            - name: Run type checking
              run: make typecheck

            - name: Run scrape
              run: make scrape

            - name: Run coverage
              run: make test-coverage

            - name: Bump version
              id: version_bump
              uses: anothrNick/github-tag-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  DEFAULT_BUMP: patch

            - name: Create Release
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: gsp/.coverage
                  tag: ${{ steps.version_bump.outputs.new_tag }}
                  generateReleaseNotes: true
