name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12

            - name: Set up Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install dependencies
              run: make install

            - name: Run formatting check
              run: make fmt-check

            - name: Run linting
              run: make lint

            - name: Run type checking
              run: make typecheck

            - name: Set up scraper
              run: make install-scraper

            - name: Run scraper
              run: make scrape

            - name: Publish scraper artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: scraper-artifacts
                  path: nsp/data/*csv
