name: CD

on:
    schedule:
        - cron: "0 5 * * *"

jobs:
    CD:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Set up Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install dependencies
              run: make install

            - name: Install Scraper
              run: make install-scraper

            - name: Run scraper
              run: make scrape

            - name: Publish scraper artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: scraper-artifacts
                  path: nsp/data/*csv
