name: CD

on:
    schedule:
        - cron: "0 17 * * 1-5"

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Set up Poetry
              run: |
                  pip install poetry
                  poetry --version

            - name: Install dependencies
              run: make install

            - name: Setup Environment
              run: |
                  echo "DB_USER=${{secrets.DB_USER}}" >> ./gsp/.env
                  echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> ./gsp/.env
                  echo "DB_NAME=${{secrets.DB_NAME}}" >> ./gsp/.env
                  echo "CLUSTER_NAME=${{secrets.CLUSTER_NAME}}" >> ./gsp/.env

            - name: Convert Jupyter notebooks to Python scripts
              run: make convert

            - name: Run pipeline
              run: make pipeline
