name: Testing Actions

on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: testing


    steps:
      - name : Setup env
        env:
          DB_NAME : ${{ secrets.DB_NAME }}
        run: echo ${{ secrets.DB_NAME }}
